sudo: required

language: ruby

services:
  - docker

before_install:
  #- gem install serverspec
  #- gem install docker-api

script:
  #- rspec Dockerfile_spec.rb
  - sudo docker build -t pyload .
  # TODO: rspec surely is much cooler than this
  - sudo sh ./test-link.sh xdcc://eudora.sg.as.abjects.net/BEAST-XDCC/Beast-Cj-2/945
  - sudo sh ./test-link.sh xdcc://eudora.sg.as.abjects.net/BEAST-XDCC/Beast-J-085/174
  - sudo sh ./test-link.sh xdcc://eudora.sg.as.abjects.net/BEAST-XDCC/Beast-J-096/189
  - sudo sh ./test-link.sh xdcc://eudora.sg.as.abjects.net/BEAST-XDCC/Beast-PIColo-123/189
  - sudo sh ./test-link.sh xdcc://eudora.sg.as.abjects.net/BEAST-XDCC/Beast-X-047/584
  - sudo sh ./test-link.sh xdcc://eudora.sg.as.abjects.net/moviegods/\[MG\]-HD\|EU\|S\|No/380
  - sudo sh ./test-link.sh xdcc://irc.rizon.net/#NIBL/Retrofit\|Kazahana/#1
  - sudo sh ./test-link.sh xdcc://irc.rizon.net/HorribleSubs/ARUTHA-BATCH\|1080p/947
  - sudo sh ./test-link.sh xdcc://irc.rizon.net/#NIBL/AnimeDispenser/#9
  #
